Description of v_lpccc2cc
Home > v_mfiles > v_lpccc2cc.m
v_lpccc2cc
PURPOSE
V_LPCCC2PF Extrapolate complex cepstrum C=(CC)
SYNOPSIS
function c=v_lpccc2cc(cc,np)
DESCRIPTION
V_LPCCC2PF Extrapolate complex cepstrum C=(CC)
CROSS-REFERENCE INFORMATION
This function calls:
v_lpcar2cc V_LPCAR2CC LPC: Convert AR filter to complex cepstrum [CC,C0]=(AR,NP)
v_lpccc2ar V_LPCCC2AR Convert complex cepstrum to ar coefficients AR=(CC)
This function is called by:
v_lpccc2db V_LPCCC2DB Convert complex cepstrum to dB power spectrum DB=(CC,NP,NC)
v_lpccc2ff V_LPCCC2FF Convert complex cepstrum to complex spectrum FF=(CC,NP,NC)
v_lpccc2pf V_LPCCC2PF Convert complex cepstrum to power spectrum PF=(CC,NP,NC)
SOURCE CODE
function c=v_lpccc2cc(cc,np)
%V_LPCCC2PF Extrapolate complex cepstrum C=(CC)
%      Copyright (C) Mike Brookes 1998
%      Version: $Id: v_lpccc2cc.m 10865 2018-09-21 17:22:45Z dmb $
%
%   VOICEBOX is a MATLAB toolbox for speech processing.
%   Home page: http://www.ee.ic.ac.uk/hp/staff/dmb/voicebox/voicebox.html
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   This program is free software; you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation; either version 2 of the License, or
%   (at your option) any later version.
%
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You can obtain a copy of the GNU General Public License from
%   http://www.gnu.org/copyleft/gpl.html or by writing to
%   Free Software Foundation, Inc.,675 Mass Ave, Cambridge, MA 02139, USA.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
p=size(cc,2);
if nargin<2 np=p; end
if np<=p
   c=cc(:,1:np);
else
   c=v_lpcar2cc(v_lpccc2ar(cc),np);
end