Description of v_rfft
Home > v_mfiles > v_rfft.m
v_rfft
PURPOSE
V_RFFT Calculate the DFT of real data Y=(X,N,D)
SYNOPSIS
function y=v_rfft(x,n,d)
DESCRIPTION
V_RFFT     Calculate the DFT of real data Y=(X,N,D)
 Data is truncated/padded to length N if specified.
   N even:    (N+2)/2 points are returned with
             the first and last being real
   N odd:    (N+1)/2 points are returned with the
             first being real
 In all cases fix(1+N/2) points are returned
 D is the dimension along which to do the DFT
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
v_fxrapt V_FXRAPT RAPT pitch tracker [FX,VUV]=(S,FS,M,Q)
v_lpcar2db V_LPCAR2DB LPC: Convert AR coefs to power spectrum in dB DB=(AR)
v_lpcar2ff V_LPCAR2FF LPC: Convert AR coefs to complex spectrum FF=(AR,NP)
v_lpcar2pf V_LPCAR2PF Convert AR coefs to power spectrum PF=(AR,NP)
v_lpccc2db V_LPCCC2DB Convert complex cepstrum to dB power spectrum DB=(CC,NP,NC)
v_lpccc2ff V_LPCCC2FF Convert complex cepstrum to complex spectrum FF=(CC,NP,NC)
v_lpccc2pf V_LPCCC2PF Convert complex cepstrum to power spectrum PF=(CC,NP,NC)
v_lpcra2pf V_LPCAR2PF Convert AR coefs to power spectrum PF=(RA,NP)
v_modspect V_MODSPECT Calculate the modulation spectrum of a signal C=(S,FS,W,NC,P,N,INC,FL,FH)
v_sigalign V_SIGALIGN align a clean reference with a noisy signal [d,g,rr,ss]=(s,r,maxd,m,fs)
v_specsub V_SPECSUB performs speech enhancement using spectral subtraction [SS,ZO]=(S,FSZ,P)
v_specsubm V_SPECSUBM obsolete speech enhancement algorithm - use v_specsub instead
v_spendred V_SPENDRED Speech Enhancement and Dereverberation by Doire
v_spgrambw V_SPGRAMBW Draw spectrogram [T,F,B]=(s,fs,mode,bw,fmax,db,tinc,ann)
v_ssubmmse V_SSUBMMSE performs speech enhancement using mmse estimate of spectral amplitude or log amplitude [SS,ZO]=(S,FSZ,PP)
v_ssubmmsev V_SSUBMMSE performs speech enhancement using mmse estimate of spectral amplitude or log amplitude [SS,ZO]=(S,FSZ,P)
v_vadsohn V_VADSOHN implements a voice activity detector [VS,ZO]=(S,FSZ,M,P)
SOURCE CODE
function y=v_rfft(x,n,d)
%V_RFFT     Calculate the DFT of real data Y=(X,N,D)
% Data is truncated/padded to length N if specified.
%   N even:    (N+2)/2 points are returned with
%             the first and last being real
%   N odd:    (N+1)/2 points are returned with the
%             first being real
% In all cases fix(1+N/2) points are returned
% D is the dimension along which to do the DFT
%      Copyright (C) Mike Brookes 1998
%      Version: $Id: v_rfft.m 10865 2018-09-21 17:22:45Z dmb $
%
%   VOICEBOX is a MATLAB toolbox for speech processing.
%   Home page: http://www.ee.ic.ac.uk/hp/staff/dmb/voicebox/voicebox.html
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   This program is free software; you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation; either version 2 of the License, or
%   (at your option) any later version.
%
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You can obtain a copy of the GNU General Public License from
%   http://www.gnu.org/copyleft/gpl.html or by writing to
%   Free Software Foundation, Inc.,675 Mass Ave, Cambridge, MA 02139, USA.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
s=size(x);
if prod(s)==1
    y=x
else
    if nargin <3 || isempty(d)
        d=find(s>1,1);
        if nargin<2
            n=s(d);
        end
    end
    if isempty(n)
        n=s(d);
    end
    y=fft(x,n,d);
    y=reshape(y,prod(s(1:d-1)),n,prod(s(d+1:end)));
    s(d)=1+fix(n/2);
    y(:,s(d)+1:end,:)=[];
    y=reshape(y,s);
end