Description of v_yticksi
Home > v_mfiles > v_yticksi.m
v_yticksi
PURPOSE
V_YTIXKSI labels the y-axis of a plot using SI multipliers S=(AH)
SYNOPSIS
function s=v_yticksi(ah)
DESCRIPTION
V_YTIXKSI labels the y-axis of a plot using SI multipliers S=(AH)
  Inputs:  AH       axis handle [default: current axes]
 Outputs:  S        optional global SI multiplier (see usage below)
 Usage:   (1) plot(...);
              v_yticksi;
          (2) plot(...);
              ylabel(['Frequency (' v_yticksi 'Hz)']);
 The first form will label the tick marks on the y-axis of the current plot
 using SI multipliers where appropriate. This is particularly useful for log
 plots which MATLAB does not label very well.
 The second form will, if possible, use a single SI multiplier for all the tick
 marks; this global multiplier can be incorporated into the axis label as shown.
CROSS-REFERENCE INFORMATION
This function calls:
v_xyzticksi V_XYZTIXKSI labels an axis of a plot using SI multipliers S=(AX,AH)
This function is called by:
v_bark2frq V_BARK2FRQ Convert the BARK frequency scale to Hertz FRQ=(BARK)
v_cent2frq V_FRQ2ERB Convert Hertz to Cents frequency scale [C,CR]=(FRQ)
v_correlogram V_CORRELOGRAM calculate correlogram [y,ty]=(x,inc,nw,nlag,m,fs)
v_erb2frq V_ERB2FRQ Convert ERB frequency scale to Hertz FRQ=(ERB)
v_frq2bark V_FRQ2BARK Convert Hertz to BARK frequency scale BARK=(FRQ)
v_frq2cent V_FRQ2ERB Convert Hertz to Cents frequency scale [C,CR]=(FRQ)
v_frq2erb V_FRQ2ERB Convert Hertz to ERB frequency scale ERB=(FRQ)
v_frq2mel V_FRQ2ERB Convert Hertz to Mel frequency scale MEL=(FRQ)
v_mel2frq V_MEL2FRQ Convert Mel frequency scale to Hertz FRQ=(MEL)
v_phon2sone V_PHON2SONE convert PHON loudness values to SONEs s=(p)
v_spgrambw V_SPGRAMBW Draw spectrogram [T,F,B]=(s,fs,mode,bw,fmax,db,tinc,ann)
SOURCE CODE
function s=v_yticksi(ah)
%V_YTIXKSI labels the y-axis of a plot using SI multipliers S=(AH)
%
%  Inputs:  AH       axis handle [default: current axes]
%
% Outputs:  S        optional global SI multiplier (see usage below)
%
% Usage:   (1) plot(...);
%              v_yticksi;
%
%          (2) plot(...);
%              ylabel(['Frequency (' v_yticksi 'Hz)']);
%
% The first form will label the tick marks on the y-axis of the current plot
% using SI multipliers where appropriate. This is particularly useful for log
% plots which MATLAB does not label very well.
% The second form will, if possible, use a single SI multiplier for all the tick
% marks; this global multiplier can be incorporated into the axis label as shown.
%       Copyright (C) Mike Brookes 2009
%      Version: $Id: v_yticksi.m 10865 2018-09-21 17:22:45Z dmb $
%
%   VOICEBOX is a MATLAB toolbox for speech processing.
%   Home page: http://www.ee.ic.ac.uk/hp/staff/dmb/voicebox/voicebox.html
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   This program is free software; you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation; either version 2 of the License, or
%   (at your option) any later version.
%
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You can obtain a copy of the GNU General Public License from
%   http://www.gnu.org/copyleft/gpl.html or by writing to
%   Free Software Foundation, Inc.,675 Mass Ave, Cambridge, MA 02139, USA.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ~nargin
    ah=gca;
end
if nargout
s=v_xyzticksi(2,ah);
else
    v_xyzticksi(2,ah);
end